[2025-08-18T21:22:21.177+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:22:19.969882+00:00 [queued]>
[2025-08-18T21:22:21.191+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:22:19.969882+00:00 [queued]>
[2025-08-18T21:22:21.193+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T21:22:21.219+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-18 21:22:19.969882+00:00
[2025-08-18T21:22:21.226+0000] {standard_task_runner.py:60} INFO - Started process 2325 to run task
[2025-08-18T21:22:21.233+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'manual__2025-08-18T21:22:19.969882+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpj495lepu']
[2025-08-18T21:22:21.239+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask dvc_pull_data
[2025-08-18T21:22:21.343+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:22:19.969882+00:00 [running]> on host 2e4674d7276b
[2025-08-18T21:22:21.480+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T21:22:19.969882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T21:22:19.969882+00:00'
[2025-08-18T21:22:21.483+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T21:22:21.485+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --force']
[2025-08-18T21:22:21.497+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T21:22:32.644+0000] {subprocess.py:93} INFO - No remote provided and no default remote set.
[2025-08-18T21:22:32.645+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-18T21:22:32.829+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T21:22:32.881+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250818T212219, start_date=20250818T212221, end_date=20250818T212232
[2025-08-18T21:22:32.918+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-18T21:22:32.953+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
