[2025-08-20T17:52:42.257+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_add_commit_model manual__2025-08-20T17:47:18.117501+00:00 [queued]>
[2025-08-20T17:52:42.308+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_add_commit_model manual__2025-08-20T17:47:18.117501+00:00 [queued]>
[2025-08-20T17:52:42.310+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-20T17:52:42.383+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_add_commit_model> on 2025-08-20 17:47:18.117501+00:00
[2025-08-20T17:52:42.406+0000] {standard_task_runner.py:60} INFO - Started process 479 to run task
[2025-08-20T17:52:42.426+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_add_commit_model', 'manual__2025-08-20T17:47:18.117501+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpdgx6kksd']
[2025-08-20T17:52:42.446+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask dvc_add_commit_model
[2025-08-20T17:52:42.713+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_add_commit_model manual__2025-08-20T17:47:18.117501+00:00 [running]> on host bd9202be787f
[2025-08-20T17:52:43.258+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_add_commit_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T17:47:18.117501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T17:47:18.117501+00:00'
[2025-08-20T17:52:43.260+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T17:52:43.270+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "cd /opt/***/Customer_Churn_Prediction_Pipeline && git config --global --add safe.directory /opt/***/Customer_Churn_Prediction_Pipeline && dvc add models/churn_model.pkl && git add models/churn_model.pkl.dvc models/.gitignore && git commit -m 'Add trained model to DVC' || echo 'Git commit completed or nothing to commit'"]
[2025-08-20T17:52:43.311+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T17:52:46.018+0000] {subprocess.py:93} INFO - ERROR: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[2025-08-20T17:52:46.716+0000] {subprocess.py:93} INFO - Git commit completed or nothing to commit
[2025-08-20T17:52:46.720+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-20T17:52:46.858+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_add_commit_model, execution_date=20250820T174718, start_date=20250820T175242, end_date=20250820T175246
[2025-08-20T17:52:46.967+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-20T17:52:47.061+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
