[2025-08-18T21:05:57.539+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:05:56.718197+00:00 [queued]>
[2025-08-18T21:05:57.558+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:05:56.718197+00:00 [queued]>
[2025-08-18T21:05:57.560+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T21:05:57.595+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-18 21:05:56.718197+00:00
[2025-08-18T21:05:57.605+0000] {standard_task_runner.py:60} INFO - Started process 1666 to run task
[2025-08-18T21:05:57.613+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'manual__2025-08-18T21:05:56.718197+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpoyatd700']
[2025-08-18T21:05:57.618+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask dvc_pull_data
[2025-08-18T21:05:57.706+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-18T21:05:56.718197+00:00 [running]> on host 2e4674d7276b
[2025-08-18T21:05:57.832+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T21:05:56.718197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T21:05:56.718197+00:00'
[2025-08-18T21:05:57.835+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T21:05:57.837+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --force']
[2025-08-18T21:05:57.853+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T21:06:09.189+0000] {subprocess.py:93} INFO - M       models/churn_model.pkl
[2025-08-18T21:06:09.194+0000] {subprocess.py:93} INFO - No remote provided and no default remote set.
[2025-08-18T21:06:09.195+0000] {subprocess.py:93} INFO - 1 file modified
[2025-08-18T21:06:09.346+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T21:06:09.379+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250818T210556, start_date=20250818T210557, end_date=20250818T210609
[2025-08-18T21:06:09.416+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-18T21:06:09.447+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
